---
 - name:My Playbook to config web VM
   host: webservers
   become: true
   task:

  - name: docker.io
    apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present
  - name: Install pip3
    apt:
        force_apt_get: yes
        name: python3-pip
        state: present
  - name: download and launch a docker web container
    docker_container:
        name: dvwa
        image: cybersecurity/dvwa
        state: started
        published_ports: 80:80
 - name: Enable docker service
   systemd:
        name: docker
        enabled: yes
